### ISSUE TITLE
Indicators for multi-monitor

### ISSUE THREAD

**Issue by christian-heusel** [yeahitsjan/pawxel#12]
Heyhey, so I just noticed that when one does a fullscreen screenshot 
https://mathphys.info/~chris/Screenshots2023-04-21_12:59:28.png

Its sometimes a bit hard to see what is actually which because the preview is rather small. Maybe it would make sense to add indicators like I've sketched it here:

![Untitled](https://user-images.githubusercontent.com/26827864/233621355-b19df147-2989-4459-98f0-94689bbc7236.png)

But that is only one solution to the problem, maybe you have a better Idea on how to make it clear which button does what 😊

**Comment by yeahitsjan** [comment]
Would make absolutely sense. I see what I can do.. 😄

**Comment by yeahitsjan** [comment]
I implemented it in https://github.com/yeahitsjan/pawxel/commit/08a4b1e86c9e30e3cdf74afdb111fbef0b21dc13.
The button itself needs some work as the image isn't always centered. For example with a vertical setup it currently looks like the following:

![image](https://user-images.githubusercontent.com/74990847/236335132-a1dfbf4d-80c2-4297-9846-54c6292cc0a1.png)

I keep this on track but close the issue as the feature itself is implemented.

**Comment by christian-heusel** [comment]
Very nice, thanks for implementing it!
