### ISSUE TITLE
virustotal scan

### ISSUE THREAD

**Issue by BadAtGithub** [yeahitsjan/pawxel#23]
![Screenshot 2024-06-06 073702](https://github.com/yeahitsjan/pawxel/assets/148623318/7fbe2604-f1f9-44a3-a8a4-5243c104c889)
`Bkav Pro
W64.AIDetectMalware
MaxSecure

> Trojan.Malware.300983.susgen`

**Comment by yeahitsjan** [comment]
Seems like a false positive. Pawxel is using Qt under the hood and writes a RegEntry when it's autostart enabled / disabled. You can take a look into code if you want to.

Neither the app nor the ZIP is signed, which means that some scanners probably recognize this as unwilled software. Thats also why the "Windows Defender protected you" is showing up when launching the app for the first time.
