### ISSUE TITLE
Dual Monitor Support - feedback required

### ISSUE THREAD

**Issue by blaszta** [yeahitsjan/pawxel#9]
I only able to take screen shot from main monitor, the cross hair cursor doesn't show up on secondary monitor.
Full screen snip only capture main monitor.  
OS: Windows 11 64-bit

**Comment by yeahitsjan** [comment]
Thank you for reporting. I am currently actively working on that. The problem looks a bit more complex than I expected first. The technical background is described here: https://github.com/yeahitsjan/pawxel/issues/2#issuecomment-1483942295

The interesting thing is, it depends on how the monitors are set up. If, for example, your left monitor is also the first in setup and your center one your second, it just works fine. If they are switched (so left monitor is 2, center monitor is 1) the coordinates for the top left point of the whole "desktop" are ``-x, -y``. I already have a working version of this where just the preview window jumps out of bounds. I try to fix that the next weeks.

**Comment by yeahitsjan** [comment]
I created a separate branch for it.
https://github.com/yeahitsjan/pawxel/tree/fix-multi-screen

The SnipArea now draws over all screens that are available. Only the PreviewWindow now has a wrong position and jumps to a wrong point (geometry is probably wrong).

**Comment by yeahitsjan** [comment]
I did a bit testing the last days. It seems like the coordinates of the mouse pos (https://github.com/yeahitsjan/pawxel/blob/develop/source/sniparea.cpp#L30) are correct but the preview window then sets itself to the mouse pos on the primary screen only (ignoring any other screen). Thats why the preview window often jumps out of bounds and isn't displayed at the correct position.

There are two ideas I have to fix this I need to evaluate further the next days:

1. Move the window to the top left of the whole desktop (all screens) first. From there on start moving the window to the correct position.
2. Also emit the screen (or rect) where the screenshot was taken and recalculate the mouse position.

**Comment by yeahitsjan** [comment]
Hey @blaszta,

do you build Pawxel by yourself? If yes, could you test out with the last commit from this branch: https://github.com/yeahitsjan/pawxel/tree/fix-multi-screen

If not, please try with the attached 7z (inside the ZIP, github only allows 25MB).
[pawxel-110423-fix.zip](https://github.com/yeahitsjan/pawxel/files/11200814/pawxel-110423-fix.zip)

This should also fix #2. Atleast on my screen setup it works fine, no matter how I change it.

**Comment by yeahitsjan** [comment]
I can now also confirm that this works perfectly on my work computer. I would love to get more feedback so that I can release this ASAP.

**Comment by yeahitsjan** [comment]
Hey @blaszta, could you already test this?

**Comment by yeahitsjan** [comment]
Closed due to inactivity. Use #2 for tracking.
